# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `caxlsx_rails` gem.
# Please instead update this file by running `bin/tapioca gem caxlsx_rails`.

module AxlsxRails; end
class AxlsxRails::Railtie < ::Rails::Railtie; end
