# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-patron` gem.
# Please instead update this file by running `bin/tapioca gem faraday-patron`.

# Patron adapter
class Faraday::Adapter::Patron < ::Faraday::Adapter
  # source://faraday-patron//lib/faraday/adapter/patron.rb#9
  def build_connection(env); end

  # source://faraday-patron//lib/faraday/adapter/patron.rb#24
  def call(env); end

  # source://faraday-patron//lib/faraday/adapter/patron.rb#101
  def configure_proxy(session, proxy); end

  # source://faraday-patron//lib/faraday/adapter/patron.rb#81
  def configure_ssl(session, ssl); end

  # source://faraday-patron//lib/faraday/adapter/patron.rb#89
  def configure_timeouts(session, req); end

  private

  # @return [Boolean]
  #
  # source://faraday-patron//lib/faraday/adapter/patron.rb#125
  def connection_timed_out_message?(message); end
end

# source://faraday-patron//lib/faraday/adapter/patron.rb#114
Faraday::Adapter::Patron::CURL_TIMEOUT_MESSAGES = T.let(T.unsafe(nil), Array)

# Main Faraday::Patron module
module Faraday::Patron; end

# source://faraday-patron//lib/faraday/patron/version.rb#5
Faraday::Patron::VERSION = T.let(T.unsafe(nil), String)
