# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-net_http` gem.
# Please instead update this file by running `bin/tapioca gem faraday-net_http`.

class Faraday::Adapter::NetHttp < ::Faraday::Adapter
  # @return [NetHttp] a new instance of NetHttp
  #
  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#37
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil), &block); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#42
  def build_connection(env); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#62
  def call(env); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#50
  def net_http_connection(env); end

  private

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#173
  def configure_request(http, req); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#157
  def configure_ssl(http, ssl); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#89
  def create_request(env); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#105
  def perform_request(http, env); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#135
  def request_via_get_method(http, env, &block); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#143
  def request_via_request_method(http, env, &block); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#126
  def request_with_wrapped_block(http, env, &block); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#193
  def ssl_cert_store(ssl); end

  # source://faraday-net_http//lib/faraday/adapter/net_http.rb#202
  def ssl_verify_mode(ssl); end
end

# source://faraday-net_http//lib/faraday/adapter/net_http.rb#35
Faraday::Adapter::NetHttp::NET_HTTP_EXCEPTIONS = T.let(T.unsafe(nil), Array)

module Faraday::NetHttp; end

# source://faraday-net_http//lib/faraday/net_http/version.rb#5
Faraday::NetHttp::VERSION = T.let(T.unsafe(nil), String)
