# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails-controller-testing` gem.
# Please instead update this file by running `bin/tapioca gem rails-controller-testing`.

module Rails::Controller; end

module Rails::Controller::Testing
  class << self
    # source://rails-controller-testing//lib/rails/controller/testing.rb#9
    def install; end
  end
end

module Rails::Controller::Testing::Integration
  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def delete(*args, **kwargs); end

  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def get(*args, **kwargs); end

  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def head(*args, **kwargs); end

  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def patch(*args, **kwargs); end

  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def post(*args, **kwargs); end

  # source://rails-controller-testing//lib/rails/controller/testing/integration.rb#14
  def put(*args, **kwargs); end
end

class Rails::Controller::Testing::Railtie < ::Rails::Railtie; end

module Rails::Controller::Testing::TemplateAssertions
  extend ::ActiveSupport::Concern

  # Asserts that the request was rendered with the appropriate template file or partials.
  #
  #   # assert that the "new" view template was rendered
  #   assert_template "new"
  #
  #   # assert that the exact template "admin/posts/new" was rendered
  #   assert_template %r{\Aadmin/posts/new\Z}
  #
  #   # assert that the layout 'admin' was rendered
  #   assert_template layout: 'admin'
  #   assert_template layout: 'layouts/admin'
  #   assert_template layout: :admin
  #
  #   # assert that no layout was rendered
  #   assert_template layout: nil
  #   assert_template layout: false
  #
  #   # assert that the "_customer" partial was rendered twice
  #   assert_template partial: '_customer', count: 2
  #
  #   # assert that no partials were rendered
  #   assert_template partial: false
  #
  #   # assert that a file was rendered
  #   assert_template file: "README.rdoc"
  #
  #   # assert that no file was rendered
  #   assert_template file: nil
  #   assert_template file: false
  #
  # In a view test case, you can also assert that specific locals are passed
  # to partials:
  #
  #   # assert that the "_customer" partial was rendered with a specific object
  #   assert_template partial: '_customer', locals: { customer: @customer }
  #
  # source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#109
  def assert_template(options = T.unsafe(nil), message = T.unsafe(nil)); end

  # source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#60
  def process(*_arg0, **_arg1); end

  # source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#65
  def reset_template_assertion; end

  # source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#16
  def setup_subscriptions; end

  # source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#53
  def teardown_subscriptions; end
end

# source://rails-controller-testing//lib/rails/controller/testing/template_assertions.rb#14
Rails::Controller::Testing::TemplateAssertions::RENDER_TEMPLATE_INSTANCE_VARIABLES = T.let(T.unsafe(nil), Array)

module Rails::Controller::Testing::TestProcess
  # source://rails-controller-testing//lib/rails/controller/testing/test_process.rb#7
  def assigns(key = T.unsafe(nil)); end
end

# source://rails-controller-testing//lib/rails/controller/testing/version.rb#4
Rails::Controller::Testing::VERSION = T.let(T.unsafe(nil), String)
