// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import DismissController from './dismiss_controller'

import ExtendedNestedFormController from './extended_nested_form_controller'

import HelloController from './hello_controller'

import MultipleSelectController from './multiple_select_controller'
application.register('dismiss', DismissController)
application.register('extended-nested-form', ExtendedNestedFormController)
application.register('hello', HelloController)
application.register('multiple-select', MultipleSelectController)
