// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import ExtendedNestedFormController from './extended_nested_form_controller'

import HelloController from './hello_controller'
application.register('extended-nested-form', ExtendedNestedFormController)
application.register('hello', HelloController)
