// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddToCalendarController from "./add_to_calendar_controller"
application.register("add-to-calendar", AddToCalendarController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import CasaNestedFormController from "./casa_nested_form_controller"
application.register("casa-nested-form", CasaNestedFormController)

import CaseContactFormController from "./case_contact_form_controller"
application.register("case-contact-form", CaseContactFormController)

import ChartHoverController from "./chart_hover_controller"
application.register("chart-hover", ChartHoverController)

import ContactTopicsController from "./contact_topics_controller"
application.register("contact-topics", ContactTopicsController)

import CopyCourtOrdersController from "./copy_court_orders_controller"
application.register("copy-court-orders", CopyCourtOrdersController)

import CourtOrderFormController from "./court_order_form_controller"
application.register("court-order-form", CourtOrderFormController)

import CourtReportController from "./court_report_controller"
application.register("court-report", CourtReportController)

import DisableFormController from "./disable_form_controller"
application.register("disable-form", DisableFormController)

import DisclosureController from "./disclosure_controller"
application.register("disclosure", DisclosureController)

import DismissController from "./dismiss_controller"
application.register("dismiss", DismissController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IconToggleController from "./icon_toggle_controller"
application.register("icon-toggle", IconToggleController)

import LocalStorageResetController from "./local_storage_reset_controller"
application.register("local-storage-reset", LocalStorageResetController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MultipleSelectController from "./multiple_select_controller"
application.register("multiple-select", MultipleSelectController)

import NavDrawerController from "./nav_drawer_controller"
application.register("nav-drawer", NavDrawerController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import SearchableSelectController from "./searchable_select_controller"
application.register("searchable-select", SearchableSelectController)

import SelectAllController from "./select_all_controller"
application.register("select-all", SelectAllController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SidebarGroupController from "./sidebar_group_controller"
application.register("sidebar-group", SidebarGroupController)

import TruncatedTextController from "./truncated_text_controller"
application.register("truncated-text", TruncatedTextController)

import TwilioController from "./twilio_controller"
application.register("twilio", TwilioController)
