# Configuration for the Labeler action
# The action is set up in ./workflows/label.yml
# See https://github.com/actions/labeler for more details
#
# Warning - Testing changes to this file can be tricky
# At the time of writing, you need to have changes committed to master for the
# Action to use them. This isn't ideal for rapid iteration. If you want to make
# changes to this file and experiment with changes, please consider testing the
# changes in a fork of this repo first. This allows you to add changes to
# master as needed and also create multiple Pull Requests to confirm labels are
# properly added.

ruby:
- changed-files:
  - any-glob-to-any-file: "**/*.rb"

erb:
- changed-files:
  - any-glob-to-any-file: "**/*.erb"

javascript:
- changed-files:
  - any-glob-to-any-file: ["**/*.js", "package*.json", "package-lock.json"]

Tests! 🎉💖👏:
- changed-files:
  - any-glob-to-any-file: ["app/javascript/__tests__/**.test.js", "spec/**/*_spec.rb"]

dependencies:
- changed-files:
  - any-glob-to-any-file: ["Gemfile*", "package*.json", "package-lock.json"]
