# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserMailer`.
# Please instead update this file by running `bin/tapioca dsl UserMailer`.

class UserMailer
  class << self
    sig { params(user: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def password_changed_reminder(user); end
  end
end
