 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/supervisor_volunteers", type: :request do
  # SupervisorVolunteer. As you add validations to SupervisorVolunteer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SupervisorVolunteer.create! valid_attributes
      get supervisor_volunteers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
      get supervisor_volunteer_url(supervisor_volunteer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_supervisor_volunteer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
      get edit_supervisor_volunteer_url(supervisor_volunteer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SupervisorVolunteer" do
        expect {
          post supervisor_volunteers_url, params: { supervisor_volunteer: valid_attributes }
        }.to change(SupervisorVolunteer, :count).by(1)
      end

      it "redirects to the created supervisor_volunteer" do
        post supervisor_volunteers_url, params: { supervisor_volunteer: valid_attributes }
        expect(response).to redirect_to(supervisor_volunteer_url(SupervisorVolunteer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SupervisorVolunteer" do
        expect {
          post supervisor_volunteers_url, params: { supervisor_volunteer: invalid_attributes }
        }.to change(SupervisorVolunteer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post supervisor_volunteers_url, params: { supervisor_volunteer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supervisor_volunteer" do
        supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
        patch supervisor_volunteer_url(supervisor_volunteer), params: { supervisor_volunteer: new_attributes }
        supervisor_volunteer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the supervisor_volunteer" do
        supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
        patch supervisor_volunteer_url(supervisor_volunteer), params: { supervisor_volunteer: new_attributes }
        supervisor_volunteer.reload
        expect(response).to redirect_to(supervisor_volunteer_url(supervisor_volunteer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
        patch supervisor_volunteer_url(supervisor_volunteer), params: { supervisor_volunteer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested supervisor_volunteer" do
      supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
      expect {
        delete supervisor_volunteer_url(supervisor_volunteer)
      }.to change(SupervisorVolunteer, :count).by(-1)
    end

    it "redirects to the supervisor_volunteers list" do
      supervisor_volunteer = SupervisorVolunteer.create! valid_attributes
      delete supervisor_volunteer_url(supervisor_volunteer)
      expect(response).to redirect_to(supervisor_volunteers_url)
    end
  end
end
