#!/bin/bash
set +e

# Bundle JS and CSS assets

echo 'Bundling js and css assets...'
docker compose run --rm web bundle install # usually will be a no-op
docker compose run --rm web yarn install   # usually will be a no-op

docker compose run --rm web yarn build
docker compose run --rm web yarn build:css
echo 'Done bundling js and css assets.'
