#!/bin/bash

# This is the data seeding script.

echo '-------------------------------------'
echo 'docker-compose run web bundle install'
docker-compose run web bundle install

# NOTE: "rails db:reset" creates the development and test databases AND seeds the database.
# This app will not work until you run this command.
echo '--------------------------------------------'
echo 'BEGIN: docker-compose run web rails db:reset'
echo '--------------------------------------------'
docker-compose run web rails db:reset
echo '------------------------------------------'
echo 'END: docker-compose run web rails db:reset'
echo '------------------------------------------'
