#!/bin/bash
set +e

echo '###########################'
echo 'BEGIN: docker-compose up -d'
echo '###########################'
echo 'View this app in your web browser at'
echo 'http://localhost:3000/'
docker-compose up -d
