#!/bin/bash

echo '-------------------------------------'
echo 'docker-compose run web bundle install'
docker-compose run web bundle install

echo '----------------------------------------------'
echo 'BEGIN: docker-compose run web rails db:migrate'
echo '----------------------------------------------'
docker-compose run web rails db:migrate
echo '--------------------------------------------'
echo 'END: docker-compose run web rails db:migrate'
echo '--------------------------------------------'

echo '-----------------------------------------'
echo 'BEGIN: docker-compose exec web rspec spec'
echo '-----------------------------------------'
docker-compose exec web rspec spec
echo '---------------------------------------'
echo 'END: docker-compose exec web rspec spec'
echo '---------------------------------------'
