name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
  pull_request:
    branches:
      - main

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        groups: ["[0, 1, 2]", "[3, 4, 5]", "[6, 7, 8]", "[9, 10, 11]"]
    uses: ./.github/workflows/rspec.yml
    secrets: inherit
    with:
      groups: ${{ matrix.groups }}
      group_count: 12 # the total number of test groups, must match the groups listed in the matrix.groups
      parallel_processes_count: 3 # the number of parallel processes to run tests in worker, must match the size of the
      # inner arrays in the matrix.groups
  combine_and_report:
    uses: ./.github/workflows/combine_and_report.yml
    needs: [rspec]
    secrets: inherit
