name: ERB lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.erb'
      - '**/*.html'
  pull_request:
    branches:
      - main
      - rfg-event-2025
    paths:
      - '**/*.erb'
      - '**/*.html'

jobs:
  erb_lint:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1
        with:
          bundler-cache: true

      - name: ERB lint
        run: bundle exec erb_lint --lint-all
