name: npm lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.jsx'
      - 'package-lock.json'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main
      - rfg-event-2025
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.jsx'
      - 'package-lock.json'
      - '.github/workflows/*.yml'

jobs:
  npm_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npm run lint
      - run: npm run test
