name: standardrb lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'bin/**'
  pull_request:
    branches:
      - main
      - rfg-event-2025
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'bin/**'

jobs:
  ruby_lint:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
        with:
          bundler-cache: true

      - name: lint
        run: bundle exec standardrb
