on:
  push:
    branches:
      - main
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@ce21845a0177fd1288cada589dd4efd2e46a27ca # v4
        with:
          CREATE_PR: true
