name: Yaml Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
        with:
          persist-credentials: false
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
