name: Yaml Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@ae1abb2821b567e96742aa776f7b62c9b6a26bc8 # v3
